### PR TITLE
core function completed

### PR DESCRIPTION
**Pull request by jackjieYYY**
Basic front-end display and back-end core functionality.
The **correct** letter and correct **position** is shown in **green**

### CODE REVIEW

**Comment by s3678272** [comment]
Checked.

**Comment by s3701549** [comment]
checked. nice

**Comment by Hengrui-Qu** [comment]
checked

**Comment by ZupeiMin** [comment]
checked

**Comment by JUNJIEZHANG-S3629270** [comment]
checked. Cool

**Pull request merged**
